-- 코드를 입력하세요
-- 온라인 상품 판매 정보 ONLINE_SALE
-- ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 온라인 상품 판매 ID, 회원 ID, 상품 ID,      판매량,        판매일

-- 오프라인 상품 판매 정보 OFFLINE_SALE
-- OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 오프라인 상품 판매 ID, 상품 ID,    판매량,        판매일

SELECT DATE_FORMAT(SALES_DATE , '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE , '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;