-- 코드를 입력하세요
-- MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH
-- 회원 ID,   회원 이름,    회원 연락처, 성별,   생년월일
SELECT MEMBER_ID,
        MEMBER_NAME,
        GENDER,
        DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE GENDER = 'W' 
    AND MONTH(DATE_OF_BIRTH) = 03
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;